version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql:delegated
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mis
      MYSQL_USER: mis
      MYSQL_PASSWORD: mis

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html:delegated
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mis
      WORDPRESS_DB_PASSWORD: mis
      WORDPRESS_DB_NAME: mis
